### ISSUE TITLE
Use http as a fallback option for non http and non https urls

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-JS#45] opened 2015-07-31 17:19 UTC
Consider using http as a fall back option for files opened as html file on file system or Windows JavaScript apps

https://github.com/Microsoft/ApplicationInsights-JS/blob/24c9a387dd1118e8e6e7bfecb1f10a4826161a8d/JavaScript/JavaScriptSDK/Initialization.ts#L142

**Comment by AlexBulankou** [comment] 2016-04-04 23:46
Dupe of https://github.com/Microsoft/ApplicationInsights-JS/issues/93

**Closed by AlexBulankou** 2016-04-04 23:46 UTC
Labels: enhancement
