### ISSUE TITLE
Typescript 2.9, ai.module.d.t.s is not a module

### ISSUE THREAD

**Issue by cmenekse** [Microsoft/ApplicationInsights-JS#615] opened 2018-05-31 21:35 UTC
When trying to use it with typescript I am seeing `ai.module.d.ts not a module`  error when using both. `@types/applicationinsights-js` and  `ai.module.d.ts`
If I do not install  `@types/applicationinsights-js`  ts tells me to install it saying type definitions not found 
If I install  `@types/applicationinsights-js` and delete `ai.module.d.ts` everything works.

I was wondering why that happens and why there are multiple type definitions?

Thank you

**Comment by jpiyali** [comment] 2018-05-31 21:40
Where are you seeing @types/applicationinsights-js?

**Comment by cmenekse** [comment] 2018-05-31 22:30
When I do not install `@types/applicationinsights-js`
I get `ai.module.d.ts  is not a module` during build and when hovered on the error in vscode it says

`Could not find a declaration file for module 'applicationInsights.js' ai.module.js  implicitly has an 'any' type  try npm install @types/applicationinsights-js`

Additionally when both `bundle/ai.module.d.ts` and  `@types/applicationinsights-js` is there/installed it does not build in recently updated `typescript 2.9.0` but it does build fine in `typescript 2.8.3` not sure how it is related though after I glanced through the changelogs.

**Comment by jpiyali** [comment] 2018-05-31 22:43
Are you trying to consume ai.module.d.ts in a commonjs typescript project?

**Comment by cmenekse** [comment] 2018-05-31 22:46
not specifically but yes , I am trying to use it with typescript and it is a commonjs typescript project.

**Comment by chrarnoldus** [comment] 2018-06-01 08:03
We're receiving the same error message when trying to upgrade from TypeScript 2.8.4 to 2.9.1 (in 2.8.4 it works fine). We're importing Application Insights like so:

```
import { AppInsights } from 'applicationinsights-js';
```

and the exact error message we're seeing is:

```
TS2306: File 'C:/blablabla/node_modules/applicationinsights-js/bundle/ai.module.d.ts' is not a module.
```

package.json has version `"applicationinsights-js": "1.0.17"`. The module style in tsconfig.json is set to commonjs.

**Comment by jpiyali** [comment] 2018-06-01 13:19
@barustum - can you take a look?

**Comment by barustum** [comment] 2018-06-01 15:01
Of course.

**Comment by barustum** [comment] 2018-06-01 23:18
possibly related to this: https://github.com/Microsoft/TypeScript/issues/24556

Although not ideal, but can you try add the following line to node_modules/applicationinsights-js/package.json:
  "types": "../node_modules/@types/applicationinsights-js/index.d.ts"

If that works, it's a work around until we publish a new SDK. Or possible go back to ts 2.8.4

**Comment by MadaraUchiha** [comment] 2018-06-10 14:44
This is affecting us too. Adding stuff in the node_modules directory is not possible for us. 

How long do you figure until there's a fix for this? (I'm willing to contribute a PR if it would help)

**Comment by ppatalong** [comment] 2018-06-11 09:45
Same here - we use AI.JS in our core project, therefore all nightly builds failed. 
We used band-aid fix:

`declare module "applicationinsights-js";` in `typings.d.ts`.

**Comment by barustum** [comment] 2018-06-11 21:24
@Dmitry-Matveev @SergeyKanzhelev Do you guys know why we have both type definition files?

**Comment by nithinmohantk** [comment] 2018-06-12 14:58
I am still having the issue on the CI Server. Any help is really appreciated.

**Comment by jpiyali** [comment] 2018-06-12 16:30
@nithinmohantk - we are looking at options. 2.9.1 is not the version that everyone is on. Can you switch to 2.8.3 until a update is avl?

**Comment by engineersamuel** [comment] 2018-06-13 23:03
Here is a workaround for 2.9.  Make sure you have a custom typings file, for example in your tsconfig.json

```
{
  ...
  "compilerOptions": {
    ...
    "typeRoots": ["@types", ...]
    ...
  }
}
```
Then in your <project>/@types/custom.d.ts:

```
declare module 'applicationinsights-js' {
    const AppInsights: Microsoft.ApplicationInsights.IAppInsights;
}
```

And voila, the import works and is typed: `import { AppInsights } from 'applicationinsights-js';`

**Comment by ayrtonmassey** [comment] 2018-06-14 13:19
@engineersamuel that didn't work for me - perhaps I'm doing it wrong?

**package.json**
```
...
"dependencies": {
    "applicationinsights-js": "1.0.18",
    ...
},
"devDependencies": {
    "@types/applicationinsights-js": "1.0.5",
    "typescript": "2.9.1",
    ...
}
...
```

**tsconfig.json**
```
...
"typeRoots": [
    "./src/@types", 
    "./node_modules/@types"
],
...
```

**src/@​types/custom.d.ts**
```ts
declare module 'applicationinsights-js' {
    const AppInsights: Microsoft.ApplicationInsights.IAppInsights;
}
```

I'm not sure how this would solve the issue as `@types/applicationinsights-js` already contains this definition.

The solution posted by @cmenekse did work:

**package.json**
```
...
"dependencies": {
    "applicationinsights-js": "1.0.18",
    ...
},
"devDependencies": {
    "@types/applicationinsights-js": "1.0.5",
    "typescript": "2.9.1",
    ...
}
"scripts": {
    "postinstall": "del .\\node_modules\\applicationinsights-js\\bundle\\ai.module.d.ts",
    ...
}
...
```

**Comment by engineersamuel** [comment] 2018-06-14 15:45
@ayrtonmassey Remove the @types/applicationinsights-js  as the ai.module.d.ts is already provided in applicationinsights-js.  Make sure you don't have that postinstall script in there either.

I haven't dug too much in-depth on the why here, only to surmise there is conflict in reading the import vs the type defs.  Re-declaring the module with `applicationinsights-js` overrides any node_module definition and therefore works around the issue with the package itself.  And it appears that the `Microsoft.ApplicationInsights.IAppInsights` is already visible.  This is evidenced by the fact that if you comment out that custom `declare module` but still `import { AppInsights } from 'applicationinsights-js'` then you can do the following:

`const x: Microsoft.ApplicationInsights.IAppInsights = null;`

Even despite the error being present on the import.  That means the type is being read, but there is an issue with how the package is configured with 2.9, hence the requirement to re-declare to override.

**Comment by nithinmohantk** [comment] 2018-06-14 15:54
Stop wasting time on those silly code changes. The easiest option is to downgrade to 2.8.3.

Restrict your project package.json to use 2.8.3 until they fix issues in 2.9.1
update package.json to semantic or  conditional versioning: 
"typescript": ">=2.6.2 <2.8.5"

**Comment by oozusta** [comment] 2018-06-14 15:56
"downgrade from latest version of another package because nobody will fix this package". good advice.

**Comment by ayrtonmassey** [comment] 2018-06-14 17:16
@engineersamuel I tried with the following:


**package.json**
```
...
"dependencies": {
    "applicationinsights-js": "1.0.18",
    ...
},
"devDependencies": {
    "typescript": "2.9.1",
    ...
}
...
```

**tsconfig.json**
```
...
"typeRoots": [
    "./src/@types", 
    "./node_modules/@types"
],
...
```

**src/@​types/custom.d.ts**
```ts
declare module 'applicationinsights-js' {
    const AppInsights: Microsoft.ApplicationInsights.IAppInsights;
}
```

i.e. without `@types/applicationinsights-js`, but it still didn't work for me.

The solution I posted above (install `@types`, use a `postinstall` hook to remove `ai.module.d.ts`) worked for me.

**Comment by nithinmohantk** [comment] 2018-06-14 18:40
@ayrtonmassey  change your dev dependency to: 

`"devDependencies": {
    "typescript": ">=2.6.2 <2.8.5",
    ...
}`

**Comment by nithinmohantk** [comment] 2018-06-14 18:44
@oozusta just try to understand with common sense before downvoting and being sarcastic,  that it's not an Application Insights bug, but latest typescript has some feature or issue that is blocking the issue. 

All I am suggesting is to downgrade the package version in your package.json  devDependencies. 

`"devDependencies": {
    "typescript": ">=2.6.2 <2.8.5",
    ...
}`

Then do an npm install again on your project folder.

**Comment by ayrtonmassey** [comment] 2018-06-14 19:50
We know it works for 2.8.X. The issue is that the included typings break our builds in 2.9.X.

Thank you for letting us know that we have the option to downgrade.

Can the applicationinsights-js developers take a look at this for those of us who want to continue using TS 2.9.X? This is the only module I'm experiencing this issue with.

**Comment by nithinmohantk** [comment] 2018-06-14 20:05
@ayrtonmassey  My 2 cents, if you look at applicationinsights-js source code, it  is using semantic version of typescript.
 "typescript":  "2.5.3" 
Typescript 2.9 was introduced recently(May 31st 2018) only and we cannot expect all NPM module owners to start supporting it right-away .
Unless your project started using core typescript 2.9 specific features, don't go for typescript.  Having latest version, doesn't make much difference some times. 
**For example:** NPM 6.x.x version has some extended package security features, if you upgrade your Node.js to 9.x.x or 10.x.x with NPM 6.x.x, you could see so many dependency packages failing. 

It takes a while for industry to adapt typescript 2.9 and don't expect to be within few weeks.  Try using work around or downgrade until they comes back with a fix.

**Comment by ayrtonmassey** [comment] 2018-06-14 20:10
This GitHub issue has been created to track the issue, so that the applicationinsights-js team is aware there is a problem and to notify users when the issue is fixed. We have a workaround, there is no urgent need to fix the problem but there is a desire from the community to see it fixed.

Please keep any further discussion on topic.

**Comment by barustum** [comment] 2018-07-12 18:35
One of the solutions proposed for this involve not generating the ai.module.d.ts. I am curious does anyone take a dependency on this file by using the reference tag as such?
`///// <reference path="./node_modules/applicationinsights-js/bundle/ai.module.d.ts" />`

**Comment by barustum** [comment] 2018-07-17 22:17
FYI for all. We decided to stop generating the ai.module.d.ts, and let developers depend on the @types package. I am making the fix this week. Thanks

**Comment by barustum** [comment] 2018-07-24 22:32
Folks, I published a new NPM package with a beta tag. The package simply does not include ai.module.d.ts. Please give it a try and let me know if that works for you without any hacks.

`npm install applicationinsights-js@beta`

**Comment by jsheetzati** [comment] 2018-07-26 16:53
@barustum the beta package + @types/applicationinsights-js works for me without any hacks. Thanks!

**Comment by ekumlin** [comment] 2018-08-03 21:32
Is there an ETA on a production release for this fix?

**Comment by barustum** [comment] 2018-08-07 21:25
We plan to have a new SDK release next week. I'll update the thread as soon as it is released.

**Comment by Hamaze** [comment] 2018-08-13 21:58
That new beta package worked great, thanks for the interim fix.

**Comment by baywet** [comment] 2018-08-16 13:30
`"applicationinsights-js": "^1.0.19-beta.1",` and `"@types/applicationinsights-js": "^1.0.5"` worked for us! thanks!

**Comment by tjlittle** [comment] 2018-08-16 17:58
Like @baywet, I still needed the ref to `"@types/applicationinsights-js": "^1.0.5"`. I didn't investigate why.

**Comment by praneetloke** [comment] 2018-08-23 00:30
@barustum any update on when the new SDK might be released?

**Comment by barustum** [comment] 2018-08-27 18:26
Deployment is complete. latest applicationinsights-js package should contain the fix. Thanks.

**Comment by ayrtonmassey** [comment] 2018-08-28 09:28
Updated to `"applicationinsights-js": "1.0.19"`, `"@types/applicationinsights-js": "1.0.6"`. Works perfectly, thanks!

**Comment by barustum** [comment] 2018-08-28 17:57
Thanks @ayrtonmassey for confirming.

**Closed by barustum** 2018-08-28 17:57 UTC

**Comment by raghulrajnkl** [comment] 2019-03-09 13:16
its work fine

npm install --save-dev @types/googlemaps
At the beggining of your component file, type:
/// <reference types="@types/googlemaps" />
