### ISSUE TITLE
Use in Typescript class?

### ISSUE THREAD

**Issue by kkdawkins** [Microsoft/ApplicationInsights-JS#581] opened 2018-04-02 23:07 UTC
We distribute a typescript based class that is transpiled into minified-js. We would love to use AI to track exceptions along with some other custom telemetry. However, we get the below error when trying to actually use AI: 

"Uncaught TypeError: define is not a function" 

Is this a supported scenario?

**Comment by jpiyali** [comment] 2018-04-03 15:11
@kkdawkins, can you provide some details on the repro? did you use the npm package?
https://www.npmjs.com/package/applicationinsights

**Comment by kkdawkins** [comment] 2018-04-03 19:52
I did some more research, and this stems from the AMD format used by AI-JS. 

I had to use a library to convert AMD -> CommonJs. You can close this issue if this is expected.

**Comment by scott-lin** [comment] 2018-04-10 21:55
I'm running into a similar error when using the library in TypeScript. I posted a comment within https://github.com/Microsoft/ApplicationInsights-JS/issues/476 since I came across that thread first, however, perhaps this issue thread is more appropriate? The issue seem related with respect to TypeScript at least.

For what it's worth, here's how I'm using the library in TypeScript (copied from the linked issue). Is there a workaround to unblock?

**package.json** (trimmed)
```
"devDependencies": {
        "@types/applicationinsights-js": "^1.0.5"
    }
"dependencies": {
        "applicationinsights-js": "^1.0.15"
    }
```

**Usage**
```
import { AppInsights } from 'applicationinsights-js';

AppInsights.config.instrumentationKey = 'my key';
AppInsights.trackTrace('my message');
```

**Comment by scott-lin** [comment] 2018-04-16 20:38
Thanks for the suggestion. I tried out two other amd -> ES6 transpilers since we don't use browserify, but had no luck getting AppInsights-js to work.

Here are the two libraries I tried:
- https://github.com/buxlabs/amd-to-es6
- https://github.com/jonbretman/amd-to-as6

Would love to see this issue fixed by AppInsights team. We're blocked as I don't have anymore cycles to spend on workarounds.

**Comment by jpiyali** [comment] 2018-04-16 21:34
@scott-lin - Is your typescript project using commonJS or UMD or AMD for compilation? Can you provide more info on the settings as well as a stack trace.

**Comment by scott-lin** [comment] 2018-04-16 21:47
@jpiyali, as stated above in my prior comment, we're using  `CommonJs` compilation for modules.

I don't have a stack trace because my code is never invoked; it fails beforehand loading imports. The code is running on a VSTS agent and the logs do not have a stack trace. Only the error message of `define is not defined` is output.

You can see my usage example above as well.

**Comment by jpiyali** [comment] 2018-04-16 22:03
@scott-lin, we currently dont have support for this scenario in the JS SDK. We're evaluating supporting node scenarios in future by publishing CommonJS version in future. Would the Application insights node SDK work for your scenario: https://azure.microsoft.com/en-us/blog/solve-nodejs-issues-with-app-insights/

**Comment by jpiyali** [comment] 2018-04-16 22:05
Better link for node sdk: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs

**Comment by scott-lin** [comment] 2018-04-16 22:08
Thanks for the suggestion. I'll look into this option soon and hopefully get back to you within the week.

**Comment by scott-lin** [comment] 2018-04-17 05:48
Confirmed, the Node SDK works great for my scenario. Thanks again!

**Comment by jpiyali** [comment] 2018-04-17 16:53
Thanks for confirming.

**Closed by jpiyali** 2018-04-17 16:53 UTC

**Comment by andrewconnell** [comment] 2018-10-14 12:57
Am I reading this correctly that the solution is to use the Node SDK in a client-side app vs. the JS SDK... & everything is working ok? Seems strange... why even have the JS SDK then?
