### ISSUE TITLE
[BUG] ClickAnalytics throwing errors in console

### ISSUE THREAD

**Issue by cadriel** [microsoft/ApplicationInsights-JS#2075] opened 2023-05-15 19:40 UTC
Having installed the latest `applicationinsights-web` and `applicationinsights-clickanalytics-js` packages, errors are occurring in the console.

<img width="1273" alt="Screenshot 2023-05-15 at 2 30 10 PM" src="https://github.com/microsoft/ApplicationInsights-JS/assets/205520/43a433a1-f4c6-49b8-8c0f-1548f4abc06a">

`caught TypeError: Cannot read properties of undefined (reading 'core')`

Packages and versions installed are;
```
    "@microsoft/applicationinsights-clickanalytics-js": "^3.0.1",
    "@microsoft/applicationinsights-web": "^3.0.1",
```

And a snippet of how I'm installing is;

```ts
export const appInsightsPlugin = {
  install: (app: App, opts: AppInsightsOptions) => {
    const clickPluginInstance = new ClickAnalyticsPlugin()
    const clickPluginConfig = {
      autoCapture: true
    }

    const appInsightsConfig = {
      ...opts.config,
      extensions: [clickPluginInstance],
      extensionConfig: {
        [clickPluginInstance.identifier]: clickPluginConfig
      }
    }

    const appInsights = new ApplicationInsights({
      config: appInsightsConfig
    })

    appInsights.loadAppInsights()
    appInsightsPlugin.setupPageTracking(opts, app)
...
```
 
This is a Vue3 project - and Application Insights seems to run ok when loading without the Click Plugin.

If this is a mis-configuration - I'd expect an error indicating so, or something else to go on. :)

**Comment by MSNev** [comment] 2023-05-16 18:38
The `trackPageView` action of the PageAction class is referencing a non-existent `_self._clickAnalyticsPlugin.core.track(event);`

**Comment by MSNev** [comment] 2023-05-16 19:35
Ok, I believe I found the issue and it's caused by the new `onConfigChange` callback when a configuration items is changed which indirectly then causes a new `_pageAction` instance to be created which is passed `this`, however, the `this` won't necessarily be the `ClickAnalyticsPlugin` instace -- it should be `_self`

**Comment by antondrozd** [comment] 2023-05-17 10:40
@MSNev Is it known when the release with the fix will happen?

**Comment by MSNev** [comment] 2023-05-17 17:45
I don't have a date yet, but it will be in the next few weeks (if not before), once released to `npm` we remove the `fixed - waiting release` label

**Comment by MSNev** [comment] 2023-05-17 17:48
I just checked the nightly automated release pipeline and it did publish a pre-release version with the tag of "nightly3" so you could use that in the short term to pre-validate that the fix is working for you (and there is not something else). 

The nightly builds are not supported for production they are provided as a pre-testing only as each night when there are any changes checked in a new release is automatically created.

**Comment by cadriel** [comment] 2023-05-17 21:54
I installed the nightly3 release in my project (both `web` and `clickanalytics-js`) and now have new errors;

<img width="784" alt="Screenshot 2023-05-17 at 4 48 10 PM" src="https://github.com/microsoft/ApplicationInsights-JS/assets/205520/80076001-929c-4144-843a-f7a85641dfb0">

If I drop the`applicationinsights-web` package back to 3.0.1 (but keep `clickanalaytics-js` at nightly3) then I see no errors in the console.

I assume the server side app insights needs some internal version bump too?

**Comment by MSNev** [comment] 2023-05-17 22:07
This is probably because the listed sdkVersion includes the full nightly release number (which is long), but we should still not cause this. On the upside this (shouldn't) happen for the primary release

> I assume the server side app insights needs some internal version bump too?

No, this is just validation that the field is not too long, we should be truncating this on the client.

**Comment by MSNev** [comment] 2023-05-17 22:09
> If I drop theapplicationinsights-web package back to 3.0.1 (but keep clickanalaytics-js at nightly3) then I see no errors in the console.

Ok, so while not ideal (as there other changes in the core and therefore web), I think this shows that this specific issue is fixed.
I'll raise another one to truncate and fix the sdkVersion length issue so future nightly releases won't have the same issue.

**Comment by MSNev** [comment] 2023-05-17 22:11
#2079

**Comment by cadriel** [comment] 2023-05-18 00:54
Ok, thanks @MSNev for the fast turnaround. 

Looking forward to the next release. 👍🏼

**Comment by antondrozd** [comment] 2023-05-18 08:21
@MSNev @cadriel Am doing something wrong guys? Struggling to install nightly3 build

<img width="362" alt="image" src="https://github.com/microsoft/ApplicationInsights-JS/assets/24996970/0d2f54f5-6bb7-4c65-aa72-e3d9d0a00a52">

**Comment by cadriel** [comment] 2023-05-18 13:56
@antondrozd you're installing the incorrect package name, try;

```sh
npm i @microsoft/applicationinsights-clickanalytics-js@nightly3
```

**Comment by MSNev** [comment] 2023-05-19 19:10
Also back ported to v2.x https://github.com/microsoft/ApplicationInsights-JS/milestone/81

**Closed** 2023-05-25 17:26 UTC
Labels: bug, p1, released - NPM, v2.x, v3.x
