### ISSUE TITLE
trackTrace truncating the property value

### ISSUE THREAD

**Issue by giakas** [microsoft/ApplicationInsights-JS#286] opened 2016-08-05 20:02 UTC
When I have  long string in the property value in TrackTrace, I am seeing this warning
But, during trackTrace, I am seeing AI: USRACT_StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"

and the value is truncated.. 

I see this warning in console for the first track trace (which I see the truncated pros in kustos), but looks like the trackTraces after the first one never reaches appInsights.
I have to refresh the browser to get the trace again(which only works the first tracktrace call)

Need help understanding the track Trace. We are considering logging some errors using trackTrace.

Girish

**Comment by kamilszostak** [comment] 2016-08-09 18:20
Hi Girish,
thank you for reporting this issue. I'll investigate this soon. 

I have recently changed the logging logic to log each warning type only once per page view - see #279. But this should only limitation is only for internal SDK logging and should not affect trackTrace.

**Comment by giakas** [comment] 2016-08-15 23:59
Adding Amit, so that he can track this item.

**Comment by markwolff** [comment] 2019-05-15 17:07
Closing this as it was by design

**Closed by markwolff** 2019-05-15 17:07 UTC
Labels: bug
