### ISSUE TITLE
Update schema - mark fields as deprecated and retain new fields

### ISSUE THREAD

**Issue by kartang** [Microsoft/ApplicationInsights-JS#373] opened 2016-12-31 00:32 UTC
To Deprecate/Add:

- Depricate Command Name ->Add data
- Depricate dependencyTypeName -> Add type
- Depricate value -> Add duration
- Depricate count, min, max, stdDev, dependencyKind, async, dependencySource and kind

RemoteDependencyData  today accepts the following fields as parameters:

**id: string, absoluteUrl: string, commandName: string, value: number, success: boolean, resultCode: number, method?: string, properties?: Object, measurements?: Object**

With the new changes, we are deriving the commandName/data from the url. Therefore, we can remove commandName from the required set of parameters. Furthermore, may be, add "name" as a set of parameters, which could be the custom name associated with a specific dependency telemetry?

If name is present, we assign telemetry.name from the parameter as opposed to getting it from url.

**Comment by kamilszostak** [comment] 2017-01-03 15:48
Duplicate of #327.

**Closed by kamilszostak** 2017-01-03 15:48 UTC
Labels: enhancement
