### ISSUE TITLE
Uncaught TypeError at Initialization.ts when loading two instances of appinsights with different versions

### ISSUE THREAD

**Issue by eyang414** [microsoft/ApplicationInsights-JS#870] opened 2019-05-13 14:23 UTC
When loading versions 1.0 and 2.0 on a single webpage, both using the JavaScript snippet method
For v1.0: https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript
For v2.0: https://github.com/microsoft/ApplicationInsights-JS - Snippet Setup (Ignore if using NPM Setup)

This error is thrown everytime appInsights tries to run log diagnostics
![image](https://user-images.githubusercontent.com/22535690/57628797-964a2180-7568-11e9-9831-57fcfcf6c1bf.png)

Initialization.ts line 106
![image](https://user-images.githubusercontent.com/22535690/57628846-b1b52c80-7568-11e9-8626-34792c003085.png)

I would imagine it has to do with there being multiple instances of app insights trying to load its own Initialization.ts file.

**Comment by markwolff** [comment] 2019-05-13 16:11
Duplicate of #855?

**Closed by markwolff** 2019-05-13 16:11 UTC
Labels: duplicate
