### ISSUE TITLE
Can ApplicationInsights Do this like Dynatrace does?

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#901] opened 2019-05-29 14:05 UTC
Hello All,
I got these set of questions from a Performance Engineer who is trying to question Applications Insights in comparison to DynaTrace. I would really appreciate if someone can help me with these and how we can achieve it in Application Insights/Log Analytics:-
o	List all user actions (user screen button clicks) with response times, and errors
o	Ability to click on the above listed user actions/transactions and get a breakdown (% contribution) from high level methods/service calls/operations and its response time contribution
o	Ability to further break down each operation and get a breakdown of time spent at various sub-service calls
o	Ability to rollup the above per-transaction data to averages across all transactions for a period
o	All performance data is available without sampling
o	Each error is traceable to a caller and a called method/module

Appreciate help on this as I think Application Insights is powerful and can achieve things with custom queries etc but I was not able to find much myself on Microsoft Documentation so thought of checking with experts here.

**Comment by markwolff** [comment] 2019-05-29 17:13
duplicate of https://github.com/microsoft/ApplicationInsights-Home/issues/350#issuecomment-497010723

**Closed by markwolff** 2019-05-29 17:13 UTC
Labels: duplicate
