### ISSUE TITLE
[BUG] isCookieUseDisabled = true prevents AppInsights user / session from persisting across page views

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/ApplicationInsights-JS#1453] opened 2021-01-08 11:41 UTC
**Description/Screenshot**
We have set our `appInsights.config.isCookieUseDisabled` to `true`. Then we found out AppInsights is refreshing user ID and session ID every time when the page refreshes (i.e. when AppInsights is loaded). Since AppInsights is using localStorage for persisting such information, our expectation is we can still correlate page views of the same session (they should have same user ID / session ID)

**Steps to Reproduce**
* Turn on `isCookieUseDisabled`
* Refresh page and observe user ID / (automatic) session ID.

 - OS/Browser: Edge 89 on Windows 10
 - SDK Version [e.g. 22]: 1.x (but 2.x **may** have similar issue)
 - How you initialized the SDK: with standalone `ai.0.js` and `<script>` snippet on HTML web page.

**Expected behavior**
* Session should persist across page views within the timeout (30 min / 24 hr)

**Additional context**

I suspect the following code may need some update
Here is the legacy version

https://github.com/microsoft/ApplicationInsights-JS/blob/f54eb736d77de93b5cdae1a7add65766a532994d/legacy/JavaScript/JavaScriptSDK/Context/User.ts#L120-L126

Here is the current version

https://github.com/microsoft/ApplicationInsights-JS/blob/f54eb736d77de93b5cdae1a7add65766a532994d/extensions/applicationinsights-properties-js/src/Context/User.ts#L74-L81

When `Util.setCookie` fails (e.g., due to cookies being disabled), we should not remove localStorage/sessionStorage backup. Or, do we really need to remove this local storage backup at all?

**Comment by chenxinyanc** [comment] 2021-01-08 11:54
There is another problem: when `isCookieUseDisabled = true`, anonymous user id is refreshed for each page view, because unlike session ID, AppInsights does not persist it in the local storage. I'm not sure whether AppInsights 2.x SDK shares the similar behavior, but is this by design?

**Comment by MSNev** [comment] 2021-01-08 19:34
I'm currently finalizing a major update of cookie handling as part of fixing #1091 and #1434 in v2 this should be release included in a release by the end of feb (maybe sooner), because of the change the version numbers will be bumped to 2.6.0 (so the upcoming 2.5.11 won't include this change).

This issue will NOT be fixed in the legacy version as it is now in critical fix only mode (and has been for a while) -- e.g. last major fix was for the SameSite change enforced by browsers.

And generally the SDK uses the cookie disabled to indicate that you don't have consent to track, I'll check the code as part of the updated cookie handling in v2 to confirm, this will probably be next week before I get to that.

But I suspect my current assumptions are true and therefore will close this issue as the equivalent of the internal state of "Wont fix". But, I will wait until I confirm the above first. So please feel free to comment further.

**Comment by chenxinyanc** [comment] 2021-01-11 05:16
> This issue will NOT be fixed in the legacy version as it is now in critical fix only mode

I understand that and perhaps I'll apply a patch locally to address it if needed.

> And generally the SDK uses the cookie disabled to indicate that you don't have consent to track

I'm not sure about this before, but [this SO post agrees to your words](https://law.stackexchange.com/questions/30739/do-the-gdpr-and-cookie-law-regulations-apply-to-localstorage). Thus we may need to keep refreshing anonymous user ID each time user refreshes the browser page. Still, should this also apply this restriction on the automatic session ID?

**Comment by MSNev** [comment] 2021-01-20 21:18
Ok, finally managed to track this down.

As while looking at the code there it did appear that it the should be possible to re-hydrate the session id from local storage, however, the execution path for that occurs during initialization also executes a "by design" path the nullifies this as a possibility.
- The "by design" path is that during initialization of the TelemetryContext the "previous" user id is only ever read from the ai_user cookie and when the cookie is either not present (or disabled) it explicitly deletes any previously saved ai_session (cookie and local storage), this is to ensure that users are not allocated to the same session id. 

Result: when cookies are disabled the ai_user and ai_session will always be reset. So disabling cookies results in "no consent" and therefore any previously saved values are ignored.

**Closed by MSNev** 2021-01-20 21:18 UTC
