### ISSUE TITLE
Typings file doesn't declare the AppInsights exported instance

### ISSUE THREAD

**Issue by eduaglz** [Microsoft/ApplicationInsights-JS#260] opened 2016-07-11 17:07 UTC
I tried to use the AppInsights typings file for a Typescript project but apparently it doesn't not export the AppInsights instance. Also, the file doesn't specify an ambient (now named "global") module.
This was fixed by adding this to the Typings file:

```
declare module 'applicationinsights-js' {
    export let AppInsights: Microsoft.ApplicationInsights.IAppInsights;
}
```

**Comment by AlexBulankou** [comment] 2016-07-11 18:25
@eduaglz thanks for reporting! Can you include more details - where did you get the typings file?

**Comment by eduaglz** [comment] 2016-07-11 19:08
@AlexBulankou I got it from the DefinitelyTyped repository using the following command:
`typings install --save --global dt~applicationinsights-js`
Thanks!

**Comment by RobARichardson** [comment] 2016-07-13 22:27
+1

**Comment by kamilszostak** [comment] 2016-07-19 01:05
Thank you for reporting this issue. I see what the problem is and I'm working on a fix. 
I'll publish the fix to  DefinitelyTyped/applicationinsights-js.

**Comment by kamilszostak** [comment] 2016-07-20 23:29
The fix was merged into DefinitelyTyped repository. I'm closing this issue, please let us know if you still experience any issues.

**Closed by kamilszostak** 2016-07-20 23:29 UTC
Labels: bug, production
