### ISSUE TITLE
[BUG] window.appInsights.properties is marked private

### ISSUE THREAD

**Issue by IGx89** [microsoft/ApplicationInsights-JS#1232] opened 2020-03-31 00:50 UTC
**Description/Screenshot**

README.md says that `window.appInsights.properties.context.telemetryTrace.traceID` is the way to get/set the trace ID, however the properties field is [marked private in the types](https://github.com/microsoft/ApplicationInsights-JS/blob/ebb1b6adc1b56fbcb4f086ef2baacad5cab1d7af/AISKU/src/Initialization.ts#L48) so I can't access it in my code. Either it's wrongly marked private, or I need a different way to get trace ID.

Thanks for your help! Use case is to show the trace ID in the error message that we show the user after a service call failure.

**Comment by IGx89** [comment] 2020-03-31 13:53
My ugly workaround:
```js
// Pull the W3C trace context ID from AI and add it to the error message.
// See https://github.com/microsoft/ApplicationInsights-JS/issues/1232 for why the any cast is needed.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const w3cTraceId = (window.appInsights as any).properties.context.telemetryTrace.traceID;
```

**Comment by MSNev** [comment] 2020-04-01 20:36
Hi,

After investigating this issue you don't need your ugly workaround, instead you will find that the appInsights object already has a public 'context' value which is a reference to the .properties.context instance.

So the issue is basically a documentation one (after calling loadAppInsights), so I'm going to update the README to read (as below) and ensure that the context value is assigned during the construction of the instance as opposed to only during the loadAppInsights() method as it is today.

`window.appInsights.context.telemetryTrace.traceID`

**Comment by IGx89** [comment] 2020-04-01 21:07
Thanks! `window.appInsights.context` is always undefined for me when using "Snippet Setup", so if your code change makes that work then that's exactly what I need :)

**Comment by MSNev** [comment] 2020-04-02 21:47
There was an issue with the way this value was propagated to the snippet, which I've fixed with the #1236 PR, this will be included in the next release

**Comment by MSNev** [comment] 2020-04-08 03:00
Fixed deployed as NPM and next CDN channels

**Comment by MSNev** [comment] 2020-04-08 17:14
Now also fully deployed to primary CDN

**Closed by MSNev** 2020-04-08 17:14 UTC
Labels: bug
