### ISSUE TITLE
[Bug]HTTP Status code response as 0 for all telemetry requests

### ISSUE THREAD

**Issue by varunmisra23** [microsoft/ApplicationInsights-JS#1327] opened 2020-07-23 10:50 UTC
Hi Team,
I am using this component for app insights logging within my angular application. For certain users(less than 1%) all of the app insights calls return http status code 0 but works fine for rest of the users. Could you provide some insights regarding this behavior.  Sample call from har file is as follows:
ai.sdkversion used 2.5.6

[httprequesttracing.txt](https://github.com/microsoft/ApplicationInsights-JS/files/4965402/httprequesttracing.txt)

**Comment by MSNev** [comment] 2020-07-23 17:25
A http status response of zero normally means that the browser failed to resolve the domain and/or the request was blocked and looking at the JSON file included this is exactly the case

"_error": "net::ERR_NAME_NOT_RESOLVED"
for   "url": "https://dc.services.visualstudio.com/v2/track",

So either of the following will be the cause
- Network is locked down (firewall) and cannot resolve the DNS entry
- Browser has an ad blocker or some other form of blocking config

This is not inherently an issue with App Insights or version 2.5.6 (the same URL is used for all version 2.x releases)

**Comment by varunmisra23** [comment] 2020-07-24 07:28
Hi,

Thanks for looking into this and responding in such a timely manner. I have
one follow up question, I have disabled the telemetry call using ad blocker
and I have got the http status code as 0 however the error was
"net::ERR_BLOCKED_BY_CLIENT" and not "net:: ERR_NAME_NOT_RESOLVED". Is
there any other reason why "ERR_NAME_NOT_RESOLVED" error is coming? Could
this be an issue with CORS calls? I understand that this is not an issue
with the sdk but I will appreciate any helpful pointers from your end.

Thanks,
Varun

**Comment by MSNev** [comment] 2020-07-27 17:14
Sorry for the delay, based on the error message "Name not Resolved" this seems to suggest that the DNS resolution in your environment is either not resolving or blocking this domain. This could be any DNS server in your hierarchy (primary / upstream), which will be controlled by your IT department / internet provider.

I don't believe this is a general issue as I have not heard of any outages with this global DNS entry.

Cheers

Nev

**Closed** 2020-08-27 20:40 UTC
