### ISSUE TITLE
[BUG] Typescript build with 2.4.0 breaks

### ISSUE THREAD

**Issue by StefanSchoof** [microsoft/ApplicationInsights-JS#1173] opened 2020-01-29 06:11 UTC
**Description/Screenshot**
https://dev.azure.com/sschoof/espresso/_build/results?buildId=1514&view=logs&j=0a099ed4-e459-5b34-cc15-88dac43c3262&t=51a3d40f-3f24-5548-8c6e-04827d8ff082&l=37
**Steps to Reproduce**
Upgrade working Typescript build from 2.3.1 to 2.4.0
 - OS/Browser: n/a
 - SDK Version [e.g. 22]: n/a
 - How you initialized the SDK: n/a

**Expected behavior**
A version upgrade from 2.3 to 2.4 is not breaking

**Additional context**

**Comment by MSNev** [comment] 2020-01-29 08:15
This appears to be the side effect of a tighter restriction on the arguments from TS 3.7.3 being used as it compiles fine with TS 2.5.3..

I believe I understand the issue and will work on it in the morning.

**Comment by MSNev** [comment] 2020-01-30 05:06
@StefanSchoof can you confirm how are you consuming the module, while I've manually reviewed the method signatures and published a PR that will address the error, I was unable to reproduce the issue using multiple versions of TypeScript (including 3.7.3). From the error it appears that you are or maybe consuming and re-building/compiling the generated module which is causing the break as it validates against the *.d.ts? Can you confirm?

Either way, is it possible for you to assist by revalidating using this branch (MSNev/TypoFixesForTS3.7 instead of master) and using the generated code at all, this would be extremely helpful so we don't publish 2.4.1 (which we are planning to do tomorrow) and then find yet another blocking issue for you?

**Comment by MSNev** [comment] 2020-01-30 19:32
Fixed with v2.4.1

**Closed by MSNev** 2020-01-30 19:32 UTC
Labels: bug, p2

**Comment by StefanSchoof** [comment] 2020-01-30 19:50
Sorry, missed your questions. Too bad I missed a opportunity to help you.

Your fix wokred and with 2.4.1 my build is up again. Thanks for the quick fix.
