### ISSUE TITLE
How to get additional info on the AJAX Request

### ISSUE THREAD

**Issue by prat19** [microsoft/ApplicationInsights-JS#1285] opened 2020-06-05 11:48 UTC
Hi,

Here is my sample AJAX call
    $.ajax({
        type: 'POST',
        url: '../router/dashboard.php',
        dataType: 'json',
        data: {"getDashboardData": "getDashboardData"},
..........});

App Insights determines this AJAX call and and identifies the URL, however it does not identify the data like type, data type and the data field, so it is like if on a web page, I have 10 AJAX call, I am not able to identify which AJAX request is called?

Please help or suggest a way to identify which AJAX is called.
Thanks.

**Comment by MSNev** [comment] 2020-06-17 03:28
The automatic tracking of the ajax calls do not capture the data type or data content for several reasons which include possible accidental capturing of PII (personal identifying information) -- so this is by design. Generally, the URL can be used to disambiguate the actual API call you are making, However, if you do have a common single API endpoint (which its sounds like what you are talking about) then this approach doesn't work.

A solution that comes to mind is that rather than using the automatic tracking, you *could* call the appInsights.trackDependencyData() yourself (https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/src/Initialization.ts#L230) with your own additional properties included in the IDependencyTelemetry object. If you take this approach I would recommend that you create a small wrapper for the ajax call and reporting rather than just using the jQuery.ajax() method directly.

**Comment by MSNev** [comment] 2020-07-09 19:12
Closing -- assuming the above resolved the issue -- please reopen if it's still occurring.

**Closed by MSNev** 2020-07-09 19:12 UTC
