### ISSUE TITLE
Occasionally connected (html5 offline manifest) SPA applications

### ISSUE THREAD

**Issue by oising** [Microsoft/ApplicationInsights-JS#165] opened 2016-03-29 17:31 UTC
Does the AI JS client support single page applications that may occasionally be disconnected from the network? Is there a client buffer for events? If so, is there a limit? Is it using session or local storage, or just in memory? I will dig into the JS source but I think the answer to this should be part of a FAQ or otherwise visible on the documentation.

**Comment by MaxShehovtsov** [comment] 2016-03-29 17:48
Right now there's no offline buffer. Also JSSDK doesn't retry if submission fails.
Good idea to start the FAQ, thanks!

**Comment by oising** [comment] 2016-03-29 17:53
I do see usage of local storage / session storage in the JS client source though - it seems adding retry logic might not be as much work as it seems...

**Comment by MaxShehovtsov** [comment] 2016-03-29 18:01
The storage is currently used for better session id management. There's also a maintenance logic that could be turned on to analyze data loss (this is disabled by default). 
I agree that offline storage shouldn't be hard to do. I've also seen several people asking about it so it might be about a time to implement it.

**Comment by AlexBulankou** [comment] 2016-04-05 00:04
Dupe of https://github.com/Microsoft/ApplicationInsights-JS/issues/69

**Closed by AlexBulankou** 2016-04-05 00:04 UTC
Labels: enhancement
