### ISSUE TITLE
Authenticated User Id not included in PageView if contains spaces

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-JS#619] opened 2018-06-07 21:03 UTC
Hello,
The authenticated user id is not included in PageView telemetry if the user id contains a space.

**REPRO STEPS**

1. Create a new MVC Web app.
2. Edit the _Layout.cshtml to include the javascript snippit.
3. Edit the _Layout.cshtml to `setAuthenticatedUserContext()`

**Test 1** - this works!
```
var id = " 1148";
window.appInsights.setAuthenticatedUserContext(id, null, true);
```

**Test 2** - space in middle does not work
```
var id = "test 1148";
window.appInsights.setAuthenticatedUserContext(id, null, true);
```

**Test 3** - space at beginning does not work
```
var id = "     1148";
window.appInsights.setAuthenticatedUserContext(id, null, true);
```

![image](https://user-images.githubusercontent.com/28785781/41125949-cab6b7d6-6a5a-11e8-954e-8bd292f90e4d.png)

**Comment by jpiyali** [comment] 2018-06-28 22:01
@MS-TimothyMothra - would you like to contribute a fix for this?

**Comment by MarkWolff** [comment] 2018-08-02 00:42
@MS-TimothyMothra - it seems that this behavior is by design. From API docs:

https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext

> Set the authenticated user id and the account id. Use this when you have identified a specific signed-in user. Parameters must not contain spaces or ,;=|

**Closed** 2018-08-02 00:43 UTC
Labels: bug
