### ISSUE TITLE
[BUG] Same timestamp on multiple pageView-events after upgrade to 3.0.3

### ISSUE THREAD

**Issue by gjermshus** [microsoft/ApplicationInsights-JS#2180] opened 2023-10-17 12:31 UTC
**Description/Screenshot**
After we upgraded to 3.0.3 we see a unexpected behavior in our application insights logs.
Multiple pageViews in the same session suddenly end up with the same timestamp.
We started noticing this when we looked at the frequency of sessions where the time between `max(timestamp)` and `min(timestamp)` we zero. (We released the new library version into production on Friday Oct 6th.)
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/7047589/bf3853a9-559b-47aa-b080-cb574ff97476)

When we look at the actual rows ingested we can se that multiple rows gets the same value, but different `ingestion_time()`
![image](https://github.com/microsoft/ApplicationInsights-JS/assets/7047589/cf94113e-bbfb-4ab0-8f9c-98c158ab6824)

 - OS/Browser: We see this behavior in all browsers
 - SDK Version [e.g. 22]: 3.0.3
 - How you initialized the SDK:

**Expected behavior**
The timestamps should be real and not the same.

**Comment by MSNev** [comment] 2023-10-17 15:48
Can I assume that your application is a SPA? And that these page views are all occurring on the client side?

In v3.0.3 we change the way we capture the page load "start time" to use the browser's reported metrics, which might be the source of this issue.

@siyuniu-ms can you please check that whether we are applying the timestamp change to ALL page views for a page or only the first one?

I'm labeling as a bug and assigning to the next release, as I suspect this is the case. If we cannot reproduce then I'll adjust the labelling.

**Comment by gjermshus** [comment] 2023-10-17 18:16
Your assumption is correct, this is a SPA and all the page views happen on the client side.
Please let me know if I can provide you with more information!

**Comment by JakobMadsen717** [comment] 2023-10-27 14:15
I am using @microsoft/applicationinsights-web@3.0.4 

Just more info in case it matters to troubleshooting. Seeing many duplicates in AppInsight logs, my app is SPA. Seeing duplicates (groups of 2, 3 or more) with identical timestamp for Dependency and Event - but for some reason I don't get them for Page Views. I don't always get dups, some sessions have em, some don't. I get dups across devices.

**Comment by siyuniu-ms** [comment] 2023-10-27 17:23
> I am using @microsoft/applicationinsights-web@3.0.4
> 
> Just more info in case it matters to troubleshooting. Seeing many duplicates in AppInsight logs, my app is SPA. Seeing duplicates (groups of 2, 3 or more) with identical timestamp for Dependency and Event - but for some reason I don't get them for Page Views. I don't always get dups, some sessions have em, some don't. I get dups across devices.

Hi, correct me if I understand wrong. The identical timestamp is referring to start time. For depenency and event traces, those who have the same start time does not have the same ingestion time or duration time.

**Comment by JakobMadsen717** [comment] 2023-10-27 18:00
My duplicates have the same timestamp, id, duration, operation_Id, etc. Every property, in a set of duplicates, seem identical to me.

But I think this is unrelated to issue at hand. I see some duplicates dating all the way back to 2023-08-19, so I have a feeling this a Red herring, sorry about that and I will need to investigate more.

**Comment by MSNev** [comment] 2023-10-27 20:26
This normally means that you are creating multiple instances of the SDK and initializing them.

You are probably not getting them for Page views because a page view is only sent from a specific instance, while the dependency (ajax) requests are indirectly sent because each instance "hooks" the XMLHttpRequest and/or fetch API.

Which means that each "hook" instance monitors that an Ajax request occurred and sends a remote dependency call for each instance. If this is the case I would expect "multiple" calls to `track` as each instance is managing it's own batching and sending of the events.

There are 2 ways to work around this
- Make sure you only create and initialize 1 single instance of the SDK for your SPA
- Before "creating" and initializing a new instance you should call `unload()` to cause the previous instance to `unhook` itself, just "replacing" any "global" reference like the `window.appInsights` will still leave the previous instance intact and sending events for the hooked values.
-

**Comment by JakobMadsen717** [comment] 2023-10-27 22:26
Thanks MSNev, your comments put me on the path. The duplicates happen when/after my PWA updates itself so something with my service worker reloading app and in the process the "old" SDK instance keeps logging events and dependencies. I think my service worker update process just needs to unload() "old/existing" instance before cutting down the tree it's sitting on. I'll nail it down & thanks for your pointers.

**Closed** 2023-10-30 19:40 UTC
Labels: bug, p1, released - NPM
