### ISSUE TITLE
Jest broken by applicationinsights-react-js

### ISSUE THREAD

**Issue by csuich2** [microsoft/ApplicationInsights-JS#891] opened 2019-05-22 20:12 UTC
In attempting to switch from react-appinsights to application-insights-react-js, many of my Jest tests starting failing with this error:

```
  ● Test suite failed to run

    Cannot find module './cjs/react.development.js' from 'applicationinsights-react-js.js'
```

This is easily reproducible by cloning the [demo app](https://nuget.pkg.github.com/Azure-Samples/application-insights-react-demo), then attempting to run tests. You may want to consider an Azure Pipelines build to the demo app to catch this kind of thing.

**Comment by lanfear** [comment] 2019-05-24 13:07
confirmed, simple swap from final RC to this release (with the minor breaking config changes) blows up tests while the runtime code seems to work fine.  please assist.  with RC6 i had a full suite of passing tests.

**Comment by csuich2** [comment] 2019-05-24 13:29
Interesting. I believe I had the same issue with RC5, but thought it would be fixed before the final RC, so I just waited to make the switch.

**Comment by lanfear** [comment] 2019-05-24 15:00
> Interesting. I believe I had the same issue with RC5, but thought it would be fixed before the final RC, so I just waited to make the switch.

fwiw, the 'final' RC candidate i was using was from this repo `https://github.com/Azure/react-appinsights` because i was unaware of the name change.   possible there were minor variances between the new repo location and the old, i was unaware this new repo existed (if it did indeed exist before the final release).  so it's possible we were using different RCs, although i'm sure my was listed in package.json as RC6.

**Comment by hectorhdzg** [comment] 2019-05-24 23:12
We are working on fixing this issue, like @csuich2  mentioned we found it while updating the sample app and we believe is specific to [Create React App](https://facebook.github.io/create-react-app/docs/getting-started) Jest configuration, let me know if you see this error in different environments.

**Comment by Itrulia** [comment] 2019-05-27 08:59
I also encounter this when using `"next": "^8.1.0",` when starting the development server via `next` (note that you need to visit the URL first for it to compile)

**Comment by lanfear** [comment] 2019-05-28 12:50
> We are working on fixing this issue, like @csuich2 mentioned we found it while updating the sample app and we believe is specific to [Create React App](https://facebook.github.io/create-react-app/docs/getting-started) Jest configuration, let me know if you see this error in different environments.

thanks for the quick follow-up, fwiw, i can confirm i used create-react-app to bootstrap my initial application.

**Comment by valentinvoilean** [comment] 2019-06-05 11:51
until gets fixed, you can mock it:

`jest.mock('@microsoft/applicationinsights-react-js', () => ({ ReactPlugin: jest.fn() }));`

**Comment by andrewconnell** [comment] 2019-06-06 20:32
@hectorhdzg asked:
> let me know if you see this error in different environments.

Failing for me now... tests were working for my app (_SharePoint Framework + React... not created with **Create React App** jest config_) until I added the React plugin for AI so removing it for now.

**Comment by markwolff** [comment] 2019-06-06 22:15
@andrewconnell The fix landed in 2.0.1. Can you try updating your versions (both the react plugin and the web SDK) and report back the results?

**Comment by markwolff** [comment] 2019-06-06 23:06
@andrewconnell The fix for this just landed in the latest release. Can you update your web SDK and React plugin to latest version and verify that it is working now?
latest React plugin = 2.0.2
latest Web SDK = 2.0.1

**Comment by andrewconnell** [comment] 2019-06-07 18:13
It's now working... thanks @markwolff ! Can't close the issue as I'm not the OP.

**Comment by markwolff** [comment] 2019-06-07 18:18
@csuich2 going to close this for now. Reopen if it is not working for you after updating the react plugin to `2.0.2`

**Closed by markwolff** 2019-06-07 18:18 UTC

**Comment by lanfear** [comment] 2019-07-01 16:50
> The fix for this just landed in the latest release. Can you update your web SDK and React plugin to latest version and verify that it is working now?
> latest React plugin = 2.0.2
> latest Web SDK = 2.0.1

also confirm it works with the version specified, sorry it took so long for me to get back to this, business priorities pulled me away from the project for a couple week.  thanks for the quick fix.  👍
