### ISSUE TITLE
V3 Public CDN URL

### ISSUE THREAD

**Issue by IvanJosipovic** [microsoft/ApplicationInsights-JS#2139] opened 2023-08-23 14:32 UTC
What is the Public CDN URL for version 3 of the SDK?

This URL does not work:
https://js.monitor.azure.com/scripts/b/ai.3.min.js

However, specific versions do work:
https://js.monitor.azure.com/scripts/b/ai.3.0.0.min.js
https://js.monitor.azure.com/scripts/b/ai.3.0.1.min.js
https://js.monitor.azure.com/scripts/b/ai.3.0.2.min.js

**Comment by MSNev** [comment] 2023-08-23 17:29
Yes, this is currently by design and documented in the [milestone](https://github.com/microsoft/ApplicationInsights-JS/milestone/82) (probably should be a little better documented).

We are currently working through some final CDN deployment items before we promote and release v3 as `ai.3.min.js` and we are currently planning to release v3.0.3 (in a week or so to `npm` -- hopefully and then the following weeks it will rollout to the CDN (exact timeline TBD, as this is the first v3 we may just blast it all the way (as no-one can or is using this today)) as the first v3 version to be released as `ai.3.min.js`.

For reference the Work items we are going through
- Updating the Web ~Snippet~ SDK Loader to support v3
  - this includes detecting if a end-user is running IE and then automatically drops back to v2 (due to possible compatibility issues))
  - The ~snippet~ SDK Loader release / documentation will be slightly delayed until we have promoted
  - We are also considering whether this should be documented to use the `ai.3.gbl.min.js` module format by default so that if/when your runtime loads `requirejs` this doesn't stop the SDK from initializing
- Updating and releasing v2 CDN (`ai.2.min.js`) so that if both v2 and v3 are loaded into the same runtime that v2 doesn't completely trash v3 and documenting how to work around this situation when it occurs (most when your running in a framework that loads v2 while you want v3). 
  - hint: We have introduced new major version namespaces with a fallback to the standard one `Microsoft.ApplicationInsights`, `Microsoft.ApplicationInsights2` and `Microsoft.ApplicationInsights3`

Short Answer:
- We are close to finishing the above and this WILL be happening REALLY soon now.

**Comment by MSNev** [comment] 2023-09-20 21:40
Ok, I've just pushed v3.0.3 to beta and currently it's heading to the next endpoint (see the [milestone](https://github.com/microsoft/ApplicationInsights-JS/milestone/84) for the URL's and all going well this will be available tomorrow (PST) as `ai.3.gbl.min.js` and `ai.3.min.js`

**Closed** 2023-09-21 20:05 UTC
Labels: released - NPM

**Comment by MSNev** [comment] 2023-09-21 20:22
ai.3.gbl.min.js and ai.3.min.js is v3.0.3

**Comment by IvanJosipovic** [comment] 2023-09-21 20:25
thank you!
