### ISSUE TITLE
Consider capturing telemetry for calls performed using window.fetch

### ISSUE THREAD

**Issue by oising** [Microsoft/ApplicationInsights-JS#166] opened 2016-03-29 17:40 UTC
As per http://caniuse.com/#search=fetch the "fetch" implementation (an easier and more friendly replacement for using XHR) now has approximately 55% coverage for modern browsers. I think it's probably about time the AI JS client looked to add hooks for monitoring calls with this modern API.

**Comment by oising** [comment] 2016-03-29 17:42
https://fetch.spec.whatwg.org/

**Comment by MaxShehovtsov** [comment] 2016-03-29 17:42
Thanks for bringing this up. Is the suggestion to switch to this API or to add a conditional logic to use it wherever supported? Is the any advandage for using fetch (assumin XHR code is already written)?

**Comment by oising** [comment] 2016-03-29 17:45
@MaxShehovtsov It's not so much about the AI JS client using it to send data to Azure (although this surely should be on your roadmap), it's more about the JS client capturing performance telemetry on general usage of this API, just like you do already for AJAX calls using XHR.

**Comment by MaxShehovtsov** [comment] 2016-03-29 17:53
Now I see the point. Did you see any data on how popular it is? Is angular 2 using .fetch as a primary ajax mechanism?

**Comment by dnduffy** [comment] 2016-03-29 18:25
I can see value in supporting tracking it in future if the spec. is adopted but per [http://caniuse.com/#search=fetch](http://caniuse.com/#search=fetch) the support is not really there yet in Chrome and Opera unless explicitly enabled in the browser (which I doubt many users are going to do) so the actual support is currently limited to newer versions of Firefox.

**Comment by oising** [comment] 2016-03-29 19:54
@dnduffy I think you're misreading the - admittedly ambiguous - notes on caniuse. `window.fetch` is available, and has been for quite a while in chrome. It's just the usage within workers that is hidden behind the flag. Open a chrome console yourself and see ;)

**Comment by oising** [comment] 2016-03-29 19:56
@dnduffy @MaxShehovtsov The front runners in modern web frameworks Angular 2 and Aurelia both have modules for fetch. Aurelia uses a polyfill if required, so even if the platform doesn't have a fully functioning fetch, the invocation is still there to capture, right? I'd have to look to see whether they're shimming XHR or just monkey-patching the base fetch.

**Comment by kierenj** [comment] 2017-04-13 13:12
This would be a great feature for me - will it make it into a release any time soon?

**Comment by oising** [comment] 2017-04-13 16:26
This is such a fundamental part of modern web apps that I am struggling to understand why this is still open.

**Comment by kierenj** [comment] 2017-04-13 21:15
Well, that's a bit harsh.  Everyone has competing priorities, and half of OUR new web apps didn't go down the fetch route for various reasons.  But, I am enthusiastically waiting for this one.  I just don't think hyperbole will help anyone ;)

**Comment by oising** [comment] 2017-05-29 19:59
I'm just bumping the thread, albeit snottily.

**Comment by garrytrinder** [comment] 2017-11-30 16:55
Just come across this issue when using a 3rd party library in an Angular 2 app that uses fetch, which means we have some AJAX requests being tracked and others not. Is there an ETA on when this functionality might be added?

**Comment by sylvanaar** [comment] 2018-02-05 14:15
You should support the Fetch API. I fail to see why it isn't supported. We reviewed AI, and found it unsuitable to modern web applications as a result of this and lack of source map support.

**Comment by andymac4182** [comment] 2018-04-18 00:48
Is there any update on this?

**Comment by riteshbhoi** [comment] 2018-05-16 17:44
Any update on capturing fetch API calls as dependency in AI for JS. 

Currently we are using Apollo client to call graphql and it uses Fetch API, and they are not tracked as dependency calls in AI.

**Comment by BenjaBobs** [comment] 2018-05-23 11:29
We too are using the Apollo client and would like support for fetch.

**Comment by kierenj** [comment] 2018-05-23 11:30
Not trying to be mean, but for some context and impact feedback, we dropped App Insights altogether, largely because of this, and are using Elastic Stack and Sentry.

**Comment by andymac4182** [comment] 2018-05-23 13:00
Curious @kierenj What are you using to push this data from fetch to those other systems automatically?

**Comment by MaximBalaganskiy** [comment] 2018-07-20 05:14
While this is being considered (2 years now :)
https://github.com/MaximBalaganskiy/application-insights-fetch-monitor

**Comment by josundt** [comment] 2018-10-10 14:45
Please add support!

**Comment by MaximBalaganskiy** [comment] 2018-10-10 15:13
I had a PR for this which got removed until the next release.

**Comment by josundt** [comment] 2018-10-10 22:20
>           I had a PR for this which got removed until the next release.

@MaximBalaganskiy : So you expect that the PR is will be accepted and merged before the next release?

**Comment by markwolff** [comment] 2018-11-28 17:52
Functionality exists in beta of v2 SDK. It is disabled by default for now. see `disableFetchTracking` here
https://www.npmjs.com/package/@microsoft/applicationinsights-web#configuration

**Closed by markwolff** 2018-11-28 17:52 UTC
Labels: enhancement

**Comment by YoniSmolin** [comment] 2018-12-24 16:13
I am trying to track window.fetch() calls in my web application, using the beta v2 SDK, and running into some trouble. I've created a minimal web page to reproduce the issue (see [here](https://github.com/YoniSmolin/webpack-starter/tree/ApplicationInsights_FetchTracking), run `npm install` and `npm start` to launch).

The issue I'm witnessing: While it seems that the page load itself is logged in the "Operations" tab of the browser performance (on the Azure portal)

![image](https://user-images.githubusercontent.com/11846732/50403433-1aad2b00-07a7-11e9-85b2-0c57d9787b11.png)

The Ajax fetch call performed when the page is loaded is never logged in the "Dependencies" tab of the browser performance

![image](https://user-images.githubusercontent.com/11846732/50403459-4c25f680-07a7-11e9-8317-90c746d6ca04.png)

Any help or pointers towards resolving this will be much appreciated!

**Comment by markwolff** [comment] 2018-12-25 04:31
Hey @YoniSmolin, thanks for posting the repo. I was able to get the fetch request from your repo  (as is) to show up in the performance page. It is only incorrectly labeled as ajax instead of fetch. 

Can you share a network tab or fiddler trace of when the RemoteDependencyData item is sent out?
Also, add these to the config to "de-noise". With this, only 3 items should be sent in the network trace: pageview, pageviewperf, your fetch request telemetry.
```
disableFetchTracking: false,
disableAjaxTracking: true,
maxBatchInterval: 1,
enableDebug: true,
verboseLogging: true
```

![image](https://user-images.githubusercontent.com/5515583/50412080-30384a00-07d3-11e9-9b8e-cc45a5651309.png)

**Comment by YoniSmolin** [comment] 2018-12-25 07:30
Thanks @markwolff! Using the config you suggested, I've been able to see the fetch() call displayed in the "Dependencies" tab.

However, I'm still witnessing what seems to be incorrect tracking behavior: Having loaded the page multiple times

![image](https://user-images.githubusercontent.com/11846732/50415812-e7f64780-0825-11e9-906b-1aeaec6bb755.png)

I see that only a single dependency call has been logged

![image](https://user-images.githubusercontent.com/11846732/50415819-ef1d5580-0825-11e9-9c86-cc604e2bd4bb.png)

I thought this might be due to the browser caching the fetch response, so I tried adding headers to disable caching (see [here](https://github.com/YoniSmolin/webpack-starter/commit/cb63d7a9339c182d55e6b64cf55e237afc14e332)), but this had no visible effect.

Find below the contents of my "Network" tab on chrome. Note there is no "track" call following the "fetch" call, and there are only two items in the "track" call preceding it (for context, the earlier calls to "track" and "demo5282476" seen in the trace are both "OPTIONS" calls):

![image](https://user-images.githubusercontent.com/11846732/50416054-32c48f00-0827-11e9-85a5-b5d42cf05ac2.png)

**Comment by markwolff** [comment] 2018-12-25 15:13
Hey @YoniSmolin I think this is because we don't instrument fetch at all in the instrumentation snippet, which we probably should. Right now, fetch is only instrumented during initialization after the sdk has been downloaded. It will miss requests until this happens. Ajax is instrumented in the snippet, so it doesn't miss any requests. You can verify by wrapping your fetch request in a setTimeout of ~15ms.

I'll create separate issue to track this bug and ping you on it. Thanks for pointing this out!

**Comment by YoniSmolin** [comment] 2018-12-30 12:42
Thank you @markwolff for addressing my concerns. Following your suggestion, I've wrapped the fetch request in a setTimeout and indeed the request was tracked correctly and showed up in the Azure portal.

I'd like to draw your attention to yet another fetch-related issue that is preventing me from integrating the beta SDK in my application: The tracked fetch request seems to get stripped of the headers that were originally appended to it.

To reproduce the effect, I refer you again to [my sample app](https://github.com/YoniSmolin/webpack-starter/tree/ApplicationInsights_FetchWithHeader). When I run the code with the Application Insights snippet commented out, the request contains the custom header I've added:

![image](https://user-images.githubusercontent.com/11846732/50547310-39487180-0c40-11e9-9847-de51668563f7.png)

But when I enable the snippet, the request has no headers:

![image](https://user-images.githubusercontent.com/11846732/50547320-7ad91c80-0c40-11e9-9232-066e3f34b91a.png)

Is this a known issue? I will be grateful for any suggestions to work around this.

**Comment by markwolff** [comment] 2018-12-30 22:32
Thanks for pointing this out @YoniSmolin. This is indeed a bug and will be fixed in next version. You can workaround it by adding `enableCorsCorrelation: true` to your config. As a side effect, this will add `request-id` & `request-context` (`request-context` is currently disabled for fetch though) headers to all outgoing requests.

**Comment by mosdav** [comment] 2019-01-17 23:01
> Thanks for pointing this out @YoniSmolin. This is indeed a bug and will be fixed in next version. You can workaround it by adding `enableCorsCorrelation: true` to your config. As a side effect, this will add `request-id` & `request-context` (`request-context` is currently disabled for fetch though) headers to all outgoing requests.

@markwolff adding those custom headers will render all the requests to be [non-simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)  hence the browser will pre-flight the request w/ an `OPTION' request, this doubles the latency
@YoniSmolin and I would love to have `fetch` logged but w/o `request-id` header, is there a W/A we can execute to avoid this header ?

**Comment by mosdav** [comment] 2019-01-18 00:12
@markwolff  it happens for all of our ajax requests.
Here is the relevant AI configuration
```
window.appInsights = new ApplicationInsights({
    config: {
        instrumentationKey: application_insights_key,
        disableFetchTracking: false,
        maxAjaxCallsPerView: -1,
        // enableCorsCorrelation is set to 'true' as a workaround for a bug in AppInsights.
        // Without this, all Ajax calls produced by the portal will be stripped of headers.
        // Reference: https://github.com/Microsoft/ApplicationInsights-JS/issues/166#issuecomment-450591284
        enableCorsCorrelation: true,
        autoTrackPageVisitTime: true
    },
    queue: []
});

We use version 1.0.0-beta.10
```

**Comment by markwolff** [comment] 2019-01-18 01:09
@mosdav We've updated some internal packages to fix this issue. you can remove `enableCorsCorrelation: true` and "reinstall" applicationinsights-web beta.10
```
npm uninstall @microsoft/applicationinsights-web; npm install @microsoft/applicationinsights-web
```
Alternatively, you can update to `beta.11` when it gets released on Jan 21.
