### ISSUE TITLE
[BUG] Suddenly cannot load ai.2.min.js anymore due to CORS error 

### ISSUE THREAD

**Issue by sebader** [microsoft/ApplicationInsights-JS#1500] opened 2021-03-17 12:23 UTC
**Description/Screenshot**
Since yesterday there seems to be an issue when using the JS-Snippet based setup as the js file cannot be loaded anymore due to a CORS error.
![image](https://user-images.githubusercontent.com/11445087/111466417-8fbc0080-8723-11eb-9811-d12b0cbcd10f.png)

**Steps to Reproduce**

 - OS/Browser: Edge (tried different versions)
 - SDK Version [e.g. 22]: Latest snippet from the github repo here
 - How you initialized the SDK: snippet, without any changes

**Expected behavior**
The js file should load.

**Additional context**
Seems seems to have worked totally fine until ~ 8pm UTC on March 16 - as I can tell by my telemetry flow into AppInsights
![image](https://user-images.githubusercontent.com/11445087/111466702-e7f30280-8723-11eb-957b-23f1d46377ea.png)

tagging @MSNev for visibility

**Comment by JefPatat** [comment] 2021-03-17 14:52
We're experiencing exactly the same issue, since around exactly the same moment.
We're using the snippet based setup and by coincidence we found that removing the 'crossOrigin: "anonymous"' parameter the issue seems to go away, which is totally unexpected to us.
The issue is reproducible on Chrome & FF as well.

**Comment by SaulBurgos** [comment] 2021-03-17 15:49
I have the same problem with:

`src: "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js",crossOrigin: "anonymous",`

And also with the new version:

`src: "https://js.monitor.azure.com/scripts/b/ai.2.min.js",crossOrigin: "anonymous",`

Using Google Chrome and FF.

**Comment by sebader** [comment] 2021-03-17 15:50
good to know that the error is not on my side :) I'll also open a support case on this

**Comment by sebader** [comment] 2021-03-17 15:54
Everybody who has additional details to add, please do so on this thread

**Comment by carneirocorp** [comment] 2021-03-17 17:33
Any update ?

**Comment by MSNev** [comment] 2021-03-17 19:19
Investigating

**Comment by MSNev** [comment] 2021-03-17 19:39
The issue is that yesterday we changed the storage account that is used as the origin for the CDN to a new definition, however, this new definition did not have it's CORS configuration set correctly -- I've now updated it.

Based on the define TTL that was listed the CDN's may cache this for up to 60 minutes. 

Please let us know if the issue doesn't resolve in this timeframe

**Comment by sebader** [comment] 2021-03-17 19:42
thanks @MSNev for the quick turnaround! I'll watch out if it resolves in the next hour

**Comment by MSNev** [comment] 2021-03-17 19:57
> I have the same problem with:
> 
> `src: "https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js",crossOrigin: "anonymous",`
> 
> And also with the new version:
> 
> `src: "https://js.monitor.azure.com/scripts/b/ai.2.min.js",crossOrigin: "anonymous",`
> 
> Using Google Chrome and FF.

For everyones reference, both of these CDN endpoints are backed by the same storage, this enables us to publish once and both endpoints get the new bit

**Comment by sebader** [comment] 2021-03-17 20:02
@MSNev I can confirm, it just started to work again for me! :)

**Comment by MSNev** [comment] 2021-03-17 20:02
The change of the file storage is a one-off and is not something that should normally occur it was caused by adding additional resiliency, so that we can recover automatically from
- CDN provider issue (the new js.monitor.azure.com domain only)
- A storage account regional outage (all domains), we now have multiple regions so we can switch to a different region in the event of some form of regional based outage.

**Comment by MSNev** [comment] 2021-03-17 20:04
I'll leave this issue open until tomorrow, so if anyone else continues the have the issue you can comment and I'll keep an eye on it.

**Comment by SaulBurgos** [comment] 2021-03-17 21:19
Confirmed: Working Again.

Thanks

**Comment by MSNev** [comment] 2021-03-17 22:09
Based on investigations into how we can identify this sort of issue sooner both on our side and on yours, if you update your snippet to the current version (currently version 5), this will report this sort of error directly as outlined here https://github.com/microsoft/ApplicationInsights-JS/blob/master/docs/SdkLoadFailure.md

ReadMe version: 
https://github.com/Microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup

Checked in version: 
https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/snippet/snippet.min.js

**Comment by MSNev** [comment] 2021-03-19 00:28
Closing as no additional reports and local monitoring are not showing any further issues.

**Closed by MSNev** 2021-03-19 00:28 UTC
Labels: bug, cdn issue, mitigated, p1, production
