### ISSUE TITLE
App Insight Javascript integration not working with site pages forcing compatibility to IE7

### ISSUE THREAD

**Issue by t525** [microsoft/ApplicationInsights-JS#1144] opened 2019-12-18 19:24 UTC
We are in process of upgrading our pages to make them work across different browsers.  But, in the meantime is there a way to get app insight javascript to work in older versions of IE (IE7)?

**Comment by MSNev** [comment] 2019-12-19 21:45
This is a duplicate of issue  #1142, closing and will address in that issue.

For background, while we have address IE8 support in version 2.3.1 we have not yet published this version to CDN. We are going to perform some additional validation now and will publish the compatible bit to the CDN in early Jan, 2020

**Closed by MSNev** 2019-12-19 21:45 UTC

**Comment by MSNev** [comment] 2019-12-19 22:17
If you use the NPM package of 2.3.1 and host the JS file yourself everything should work fine.

**Comment by MSNev** [comment] 2019-12-19 22:30
Checked and validated that a local version of 2.3.1 initializes correctly

**Comment by t525** [comment] 2019-12-23 14:43
So is this why in IE only the initial page views are logged but not subsequent views?

**Comment by MSNev** [comment] 2019-12-26 07:23
This is because IE 6-8 (https://caniuse.com/#search=hashchange) don't support the window.location hashchange event, so we have no way to monitor the URL (efficiently) to be able to track subsequent views.

**Comment by t525** [comment] 2020-01-02 15:04
So, there is no workaround to make page views work properly for old browsers?

**Comment by markwolff** [comment] 2020-01-02 16:37
You will need to manually call `trackPageView` for each new page view if you would like it to work on older browsers.

**Comment by t525** [comment] 2020-01-02 16:59
We are currently injecting javascript to each of the pages to call trackPageView.  However, it appears that only first page view is logged and subsequent ones are not.  Does this have to do with fix that will be put out early January?

**Comment by MSNev** [comment] 2020-01-06 19:38
Unknown... If you are getting a JS error as part of calling trackPageView() then perhaps the ES3 support will fix that, however, if there is no JS error being thrown (use the F12 to track the network for reported JS errors and the console to see if anything is happening) then it's probably something else...

**Comment by t525** [comment] 2020-01-06 21:08
There were no javascript errors as far as I can see..

**Comment by MSNev** [comment] 2020-01-06 21:20
Probably, the easiest way to track down from here will be to use the browser F12 debugging tools -- although in IE7 mode it's a bit limited...

Tip: Change the snipet URL to the following to get the unminified version of 1.0.20
https://az416426.vo.msecnd.net/scripts/a/ai.1.0.20.js
As this will help debugging into the App Insights code (assuming it's somewhere in this code that is failing), although there is a downside in that the minification process fixes up some of the ES3 issues, so it's possible that the unminified version will have JS errors that the minified version doesn't.
