### ISSUE TITLE
Angular JS SPA shows all request to multiple routes under single page, need help

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-JS#886] opened 2019-05-21 22:04 UTC
Hello,
We have a SPA built on Angular and we trying to leverage Application Insights but somehow only one entry of the PAGE gets logged on Application Insights. Can someone help me here with what have I done wrong in the code (Sorry this code is developed by other developer) and I have no expereince in Angular but trying to help them integrate Application insights.
Here is my code from app-routing-module.ts

`import { NgModule, Inject } from '@angular/core';
import { Routes, Router, RouterModule, NavigationEnd, NavigationStart } from '@angular/router';
import { Http } from '@angular/http';
import { WINDOW } from './services/window.service';
import { AuthGuard } from './auth/auth.guard';
import { NavigationService } from './services/navigation.service';
import { DataService } from './services/dataservice/data.service';

declare var $: any;

export const appRoutes: Routes = [
    { path: 'zipcodeeligibility', loadChildren: './dist/zipcodeeligibility/zipcodeeligibility.module#ZipCodeEligibilityModule' },
    { path: 'businesseligibility', loadChildren: './dist/businesseligibility/businesseligibility.module#BusinessEligibilityModule', data: { prev: ['/zipcodeeligibility'] }, canLoad: [AuthGuard] },
    { path: 'emaileligibility', loadChildren: './dist/emaileligibility/emaileligibility.module#EmailEligibilityModule', data: { prev: ['/businesseligibility'] }, canLoad: [AuthGuard] },
    { path: 'basics', loadChildren: './dist/basics/basics.module#BasicsModule', data: { prev: ['/emaileligibility', '/yourbusiness', '/youremployees', '/yourproperty', '/yourvehicles', '/effectivedate'] }, canLoad: [AuthGuard] },
    { path: 'vehiclepossession', loadChildren: './dist/vehiclepossession/vehiclepossession.module#VehiclePossessionModule', data: { prev: ['/yourvehicles', '/vehicleusage'] }, canLoad: [AuthGuard] },
    { path: 'vehicleusage', loadChildren: './dist/vehicleusage/vehicleusage.module#VehicleUsageModule', data: { prev: ['/vehiclepossession', '/vehiclereview'] }, canLoad: [AuthGuard] },
    { path: 'vehicledetails', loadChildren: './dist/vehicledetails/vehicledetails.module#VehicleDetailsModule', data: { prev: ['/vehicleusage', '/vehiclereview'] }, canLoad: [AuthGuard] },
    { path: 'vehicledescription', loadChildren: './dist/vehicledescription/vehicledescription.module#VehicleDescriptionModule', data: { prev: ['/vehicledetails'] }, canLoad: [AuthGuard] },
    { path: 'vehiclereview', loadChildren: './dist/vehiclereview/vehiclereview.module#VehicleReviewModule', data: { prev: ['/vehicledescription', '/vehicleusage', '/vehicledetails', '/vehicleinformation'] }, canLoad: [AuthGuard] },
    { path: 'vehicleinformation', loadChildren: './dist/vehicleinformation/vehicleinformation.module#VehicleInformationModule', data: { prev: ['/vehiclereview'] }, canLoad: [AuthGuard] },
    { path: 'aboutvehicle', loadChildren: './dist/aboutvehicle/aboutvehicle.module#AboutVehicleModule', data: { prev: ['/vehicleinformation'] }, canLoad: [AuthGuard] },
    { path: 'quotesave', loadChildren: './dist/quotesave/quotesave.module#QuoteSaveModule' },
    { path: '', pathMatch: 'full', redirectTo: '/zipcodeeligibility' },

];

@NgModule({
    imports: [
        RouterModule.forRoot(appRoutes, { useHash: true })

    ],
    exports: [
        RouterModule
    ],
    providers: [AuthGuard, NavigationService],
    declarations: []
})

export class AppRoutingModule {
    prevLink = '';

    constructor(private route: Router, @Inject(WINDOW) public window: Window, public nav: NavigationService, public _dataService: DataService) {
        this.routeEvent(this.route);
    }

    routeEvent(router: Router) {
        router.events.subscribe(e => {
            if (e instanceof NavigationEnd) {
                this.prevLink = this.route.url;
                this.nav.setPreviousPage(this.route.url);

                //For reloading all the bootstrap components
                $(window.document).ready(function () {
                    $.getScript('/Content/scripts/angularevents.js');

                });

                window.scrollTo(0, 0);

                //run appInsights only for angular pages
                if ((<any>window).appInsights) {
                    (<any>window).appInsights.trackPageView(
                        "FirstPage", /* (optional) page name */
                        null, /* (optional) page url if available */
                        { prop1: "prop1", prop2: "prop2" }, /* (optional) dimension dictionary */
                        { measurement1: 1 }, /* (optional) metric dictionary */
                        123 /* page view duration in milliseconds */
                    );
                    const telemetryInitializer = function () {
                        (<any>window).appInsights.context.addTelemetryInitializer(function (envelope) {
                            const tags = envelope.tags;
                            if (tags && tags['ai.user.authUserId']) {
                                tags['ai.device.roleName'] = tags['THREE-UFE'];
                            }
                        });
                    };
                    if ((<any>window).appInsights.queue !== undefined) {
                        (<any>window).appInsights.queue.push(telemetryInitializer);
                    } else {
                        telemetryInitializer();
                    }
                    (<any>window).appInsights.trackPageView();
                }
            }

            if (e instanceof NavigationStart) {
                //this._dataService.Account = (<any>window).serviceData.Account;     
                //this._dataService.Policies = (<any>window).serviceData.Policies; 
                //this._dataService.getJsonObject();

                //Data Analytics
                (<any>window).dataLayer.push({
                    'event': 'pageview',
                    'pageName': e.url,
                    'referralUrl': this.prevLink,
                    'url': e.url
                });

            }
        });
    }
}

`

**Comment by markwolff** [comment] 2019-06-13 18:40
Duplicate of #889 
See https://github.com/microsoft/ApplicationInsights-JS#single-page-applications

**Closed by markwolff** 2019-06-13 18:40 UTC
Labels: duplicate
