### ISSUE TITLE
[BUG]  Angular project doesn't build after install latest version  v.2.8.0

### ISSUE THREAD

**Issue by cmonzon44** [microsoft/ApplicationInsights-JS#1807] opened 2022-04-19 14:14 UTC
Angular project doesn't build after install latest version  v.2.8.0

![image](https://user-images.githubusercontent.com/11430219/164023959-1de266ec-95b6-41ea-8f72-dd346a256a02.png)

ERROR in node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Enums/EnumHelperFuncs.d.ts:33:30 - error TS1005: ',' expected.

     [key in keyof E]: [eValue: E[keyof E], mapValue: V[keyof V]];

I should to set version 2.7.4 to build correctly again.

**Comment by MSNev** [comment] 2022-04-19 15:27
Yes, we will prepare a release which uses 2.8.0

**Comment by javier-caparo** [comment] 2022-04-19 17:04
Same here for us, using "typescript: ~3.8.3" in our package.json , which calls this dependency: "Microsoft Application Insights JavaScript SDK - Core" ( @microsoft/applicationinsights-core-js , version : 2.8.0)

-----
ERROR in node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Enums/EnumHelperFuncs.d.ts:33:30 - error TS1005: ',' expected.

33     [key in keyof E]: [eValue: E[keyof E], mapValue: V[keyof V]];

                           ~

node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Enums/EnumHelperFuncs.d.ts:33:52 - error TS1005: ',' expected.

33     [key in keyof E]: [eValue: E[keyof E], mapValue: V[keyof V]];

-----

Workaround:

a) we created the package-lock.json and then modifying the dependency version of @microsoft/applicationinsights-core-js to 2.5.10.

and then execute 
b) npm ci 

c) npm build

it works!!

**Comment by MSNev** [comment] 2022-04-19 18:37
v2.8.1 of the AngularPlugin which uses AI v2.7.4 is now published
https://www.npmjs.com/package/@microsoft/applicationinsights-angularplugin-js/v/2.8.1

We plan to also release a v2.9.0 (which uses AI v2.8.0 shortly as well)

**Comment by MSNev** [comment] 2022-04-19 18:39
@javier-caparo Can you upgrade to TypeScript 4.x? Or do you need to stay on TS 3.x?

**Comment by MSNev** [comment] 2022-04-19 20:26
I have a v2.9.0 version of the angular plugin ready to publish, but I'm going to delay the release a little as it WILL require AI v2.8.0 (which has the above TS 4.x typing syntax) and it also uses new API's that only exist in 2.8.x so using a lock file to push back the version won't work.

**Comment by alexisHuaracMallqui** [comment] 2022-04-19 23:22
hello, did you find any solution for the versions that use typescript 3.x ?

**Comment by MSNev** [comment] 2022-04-19 23:48
Yes, the PR #1810 fixes the issue but GitHub and DevOps are having issues talking with each other -- which is blocking merging the PR. Once the PR is merged we are planning to release a v2.8.1 with the fix later this week.

**Comment by cmonzon44** [comment] 2022-04-19 23:54
during the fix isn't available, i set in my package.json  explicit version : "@microsoft/applicationinsights-web": "2.7.4",

**Comment by FabioColan** [comment] 2022-04-25 22:03
Hello @MSNev , is going to work on some solution for TypeScript 3.x

**Comment by MSNev** [comment] 2022-04-25 22:31
We released the following on Friday April, 22nd, both (should) work with TypeScript 3.x and 4.x

- The Angular11 v2.7.1 uses ApplicationInsights v2.7.4, we are not planning on updating this to v2.8.x (or later), this was published to address the issue caused by the ApplicationInsights v2.8.x release and the package.json scoping.
- Angular13 v2.9.0 uses ApplicationInsights v2.8.1

The TypeScript 3.x issue exists with Applicaiton Insights v2.8.0

**Comment by MSNev** [comment] 2022-04-27 20:26
v2.8.1 is now fully deployed

**Comment by MSNev** [comment] 2022-04-27 23:48
Rolled back CDN to v2.7.4 due to #1822

**Comment by MSNev** [comment] 2022-05-17 18:46
v2.8.3 is now fully deployed to the CDN

**Closed by MSNev** 2022-05-17 18:46 UTC
Labels: ts# compat, released - NPM
