### ISSUE TITLE
[Proposal] Change module to CommonJS as opposed to AMD

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/ApplicationInsights-JS#393] opened 2017-01-31 21:31 UTC
This is causing issue when implementing ApplicationInsights-JS in a server-rendered (clientside app) solution.

    ReferenceError: define is not defined

Is there any reason it was being implemented with AMD, and is it possible to have both solutions (if needed) so we can pull the correct one in our case?

**Comment by kamilszostak** [comment] 2017-02-01 18:07
Duplicate of #301. I assigned the work for the next release - [1.1.0](https://github.com/Microsoft/ApplicationInsights-JS/milestone/22).

**Closed by kamilszostak** 2017-02-01 18:07 UTC

**Comment by MarkPieszak** [comment] 2017-02-01 18:13
Apologies for not seeing that one! Thanks so much :+1:
