### ISSUE TITLE
Telemetry data is lost when telemetry API calls fail

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-JS#82] opened 2015-11-23 19:55 UTC
It appears that when sending telemetry to the app insights API fails, the telemetry is completely lost.  I think there would be a lot of benefit in a store and forward model (write telemetry out to local storage first, attempt to send it after).

**Comment by AlexBulankou** [comment] 2016-04-05 00:05
Dupe of https://github.com/Microsoft/ApplicationInsights-JS/issues/69

**Closed by AlexBulankou** 2016-04-05 00:05 UTC
Labels: enhancement
