### ISSUE TITLE
IE10 - Telemetry failing to send

### ISSUE THREAD

**Issue by forktrucka** [Microsoft/ApplicationInsights-JS#135] opened 2016-02-22 00:17 UTC
No page view or event data is being returned by my site when viewed from IE10. Requests are still being reported.

I have noticed that when using IE10, telemetry is failing to send. You get similar issues to below reported. Tested in IE8, IE9,IE11, latest Chrome and firefox.

Custom lib location:

Telemetry transmission failed, some telemetry will be lost: [object Error]{ stack: 'Error: Access is denied.

   at _xhrSender (https://[blah].azurewebsites.net/scripts/lib/ai.0.15.0-build58334.min.js:1:22545)
   at triggerSend (https://[blah].azurewebsites.net/scripts/lib/ai.0.15.0-build58334.min.js:1:22215)
   at Anonymous function (https://[blah].azurewebsites.net/scripts/lib/ai.0.15.0-build58334.min.js:1:21643)', message: 'Access is denied.
', name: 'Error' 

No lib specified:

AI (Internal): Telemetry transmission failed, some telemetry will be lost: Error properties: {"exception":"[object Error]{ stack: 'Error: Access is denied.\r\n\n   at open (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:11217)\n   at _xhrSender (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:34476)\n   at triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:33992)\n   at flush (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:69470)\n   at Anonymous function (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:58106)', message: 'Access is denied.\r\n', name: 'Error'"} 

I'm using a plain VS 2015 - ASP.NET MVC template site and hosting in Azure.

**Comment by SergeyKanzhelev** [comment] 2016-02-22 18:22
Dup for https://github.com/Microsoft/ApplicationInsights-JS/issues/76 Please check out response there

**Comment by forktrucka** [comment] 2016-02-22 20:24
Have tried the solution outlined in the other issue. flush doesn't work anywhere it seems.

var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"[key]"            
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
        appInsights.trackEvent('Test Event', {}, {});
        appInsights.flush();

SCRIPT438: Object doesn't support property or method 'flush' 
[site].azurewebsites.net, line 78 character 9

**Comment by SergeyKanzhelev** [comment] 2016-02-22 21:28
Try 
``` javascript
appInsights.queue.push(function(){appInsights.flush();})
```
as flush got defined only after script fully loaded.

**Comment by forktrucka** [comment] 2016-02-23 00:05
hey, i've tried it, triple checked it's the first script in the head and across my browsers. Still not working.

Code:
```
<script type="text/javascript">

        var appInsights = window.appInsights || function(config) {
            function r(config) {
                t[config] = function() {
                    var i = arguments;
                    t.queue.push(function() { t[config].apply(t, i) })
                }
            }

            var t = { config: config }, u = document, e = window, o = "script", s = u.createElement(o), i, f;
            for (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) r("track" + i.pop());
            return r("setAuthenticatedUserContext"), r("clearAuthenticatedUserContext"), config.disableExceptionTracking || (i = "onerror", r("_" + i), f = e[i], e[i] = function(config, r, u, e, o) {
                var s = f && f(config, r, u, e, o);
                return s !== !0 && t["_" + i](config, r, u, e, o), s
            }), t
        }({
            instrumentationKey: "[key]"
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
        appInsights.trackEvent('Test Event', {}, {});
        appInsights.queue.push(function() { appInsights.flush(); });
    </script>
```

Error:

AI (Internal): Telemetry transmission failed, some telemetry will be lost: Error properties: {"exception":"[object Error]{ stack: 'Error: Access is denied.\r\n\n   at open (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:11217)\n   at _xhrSender (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:34476)\n   at triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:33992)\n   at flush (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:69470)\n   at Anonymous function (https://[site].azurewebsites.net/:31:45)\n   at emptyQueue (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:73922)\n   at Anonymous function (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:76689)\n   at Anonymous function (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:76338)\n   at Global code (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:76319)', message: 'Access is denied.\r\n', name: 'Error'"} 


Works in:

Chrome
IE8, IE9, IE11
Firefox

Update:
I tried it using browser stack on Windows 7 with IE 10 - v10.0.9200.17229 (KB3021952) and it did work. 

Checked my test instance all of my test browsers are RTM. It appears that it does not work on v10.0.9200.16384 (RTM). Will update my browser and hopefully that sorts it.

**Comment by MaxShehovtsov** [comment] 2016-02-23 00:27
We're subscribed to window.onbeforeunload to flush everything before going away from page. Last time I checked IE has issues with that, it still was able to send everything before onbeforeunload. If you do flush as Sergey recommended - do you start seeing telemetry in the portal?

**Comment by forktrucka** [comment] 2016-02-23 00:48
Yes I do :) 

![image](https://cloud.githubusercontent.com/assets/17393932/13237876/ffdb1b50-da33-11e5-9ede-313ed50fb3d8.png)

**Comment by MaxShehovtsov** [comment] 2016-02-23 04:03
Ok. I believe you still see the errors too, they should not affect the monitoring. My proposal is to expose a switch in jssdk to enable/disable onbeforeunload as it doesn't work in IE. I wouldn't disable it in IE unconditionally as this seems to be IE bug which I hope will be fixed at some point.

**Comment by forktrucka** [comment] 2016-02-23 21:27
@MaxShehovtsov i updated my IE10 test browser to v10.0.9200.17229 (KB3021952)... and i can see that it works now without error.

However, I did also find that by adding the flush code, it seemed to kill IE11 and Chrome in my implementation, i stopped checking after that. 

Suspecting this piece of code to be the issue and based on your comment about onbeforeunload etc, i put a condition to only flush (as suggested by @SergeyKanzhelev) when using IE10 and it seems to have fixed it.

I have now tried this on IE8 - IE11, Chrome, Firefox, Opera, Safari (v5.1 on PC..yuck i know), Mobile Safari on iPad, Mobile Opera on iPad, Mobile Firefox on iPad, Mobile Chrome on iPad and it seems to work without error. Analytics are being returned and continuously exported to Azure SQL DB as expected.

The relevant code is here:
```
 var GetIEVersion = function() {
        return /MSIE\s/.test(navigator.userAgent) && parseFloat(navigator.appVersion.split("MSIE")[1]);
    }

    var config = module.config();
    var IEVersion = GetIEVersion();
    
    function getAppInsight() {

        var appInsights = window.appInsights || function (config) {
            function r(config) {
                t[config] = function () {
                    var i = arguments;
                    t.queue.push(function () { t[config].apply(t, i) })
                }
            }

            var t = { config: config }, u = document, e = window, o = "script", s = u.createElement(o), i, f;
            for (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) r("track" + i.pop());
            return r("setAuthenticatedUserContext"), r("clearAuthenticatedUserContext"), config.disableExceptionTracking || (i = "onerror", r("_" + i), f = e[i], e[i] = function (config, r, u, e, o) {
                var s = f && f(config, r, u, e, o);
                return s !== !0 && t["_" + i](config, r, u, e, o), s
            }), t
        }({
            instrumentationKey: config.analyticsKey,
            disableTelemetry: !config.enabled
        });

        window.appInsights = appInsights;
        return appInsights;
    }

    function AnalyticsController() {
        var controller = this;

        this.push = function () {

            if (IEVersion == 10) {
                var telemetry = getAppInsight();

                telemetry.queue.push(function () {
                    telemetry.flush();
                });
            }
        };


        this.trackEvent = function (name, properties, measurements) {

            var telemetry = getAppInsight();
            telemetry.trackEvent(name, properties, measurements);
            controller.push();
        };

        this.trackPageView = function() {

            var telemetry = getAppInsight();
            telemetry.trackPageView();
            controller.push();
        };
```

So for this to work in IE10 my findings are:

1. End users must not be running IE10 RTM - must have an updated browser. Looks like there is no way to avoid this.
2. Use the  appInsights.queue.push(function () { appInsights.flush(); }); method only when using IE10. Without which you don't seem to receive any telemetry even if you have updated IE10.

**Comment by forktrucka** [comment] 2016-02-23 22:02
Browser Versions:

IE8 - 8.0.7601.17514
IE9 - 9.0.8115.16421
IE10 - 10.0.9200.17640
IE11 - 11.0.9600.18161 (Analytics error/warning on RTM  11.0.9600.16384)
Chrome - 48.0.2564.116 m
Safari - 5.1.7 (7534.57.2)
Firefox - 44.0.2
Opera - 35.0.2066.68

iPad
Mobile Opera - 12.1.1
Mobile Chrome - 48.2564.104
Mobile Safari - IOS 9.2.1
Mobile Firefox - 2.0

**Comment by AlexBulankou** [comment] 2016-04-04 23:49
Dupe of https://github.com/Microsoft/ApplicationInsights-JS/issues/69

**Closed by AlexBulankou** 2016-04-04 23:49 UTC
